version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - TABLE_NAME=votesysg
      - KEY=[key]