version: '3.4'

services:
  votesyweb:
    image: votesyweb
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5002:5002
    environment:
      - apiUrl=http://localhost:10000
      - resultsURL="http://localhost:8080"
      - RabbitMQHost="192.168.239"