version: '3.4'

services:
  votesy-results:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - connectionString=[ConnectionString]
      - voteUrl=http://localhost:5002