version: '3.4'

services:
  votesy-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7999:80
    environment:
      - RABBITMQ_HOST=[ConnectionString]
      - REDIS_HOST=[ConnectionString]

