version: '3.4'

services:
  votesy-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - QueueConnectionString=[ConnectionString]
      - Key=[Key]
      - TableName=votes
      - AccountName=votesysg
