name: Build Votesy API
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        cache: true
        cache-dependency-path: votesy-api/go.sum

    - name: Install Dependencies
      run: |
        go get -u github.com/Azure/azure-sdk-for-go/sdk/data/aztables
        go get -u github.com/aidarkhanov/nanoid
        go get -u github.com/gorilla/mux

    - name: Build
      run: go build -v ./votesy-api/api.go