name: Build Votesy API
on: [push]

defaults:
  run:
    working-directory: votesy-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.15

    - name: Install Dependencies
      run: |
        go get .
        go get github.com/Azure/azure-sdk-for-go/sdk/data/aztables
        go get github.com/aidarkhanov/nanoid
        go get github.com/gorilla/mux

    - name: Build
      run: go build -v ./api.go