name: Build Votesy API
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

on: [push]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./votesy-api
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
        with:
            platforms: linux/arm64, linux/amd64
      - name: Log into registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: "{{defaultContext}}:votesy-api"
          platforms: linux/arm64, linux/amd64
          push: true
          tags: |
            ghcr.io/ckriutz/votesy-api:latest
            ghcr.io/ckriutz/votesy-api:${{ github.run_number }}
            labels: ${{ steps.meta.outputs.tags }}