name: Build Votesy API
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches: [ "main" ]
    paths:
    - .github/workflows/votesy-api-build.yml
    - "votesy-api/**"
    - "src/votesy-api/**"


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./votesy-api
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
        with:
            platforms: linux/arm64, linux/amd64
      - name: Log into registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push
        uses: docker/build-push-action@v6.9.0
        with:
          context: ./votesy-api
          file: ./votesy-api/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/ckriutz/votesy-api:latest
            ghcr.io/ckriutz/votesy-api:${{github.run_number}}